- site/index.html
The png logo looks awful when scaled down in MS Edge, so it's better to use a smaller png or to just switch to svg
> swap the navbar logo to svg

- site/index.html
> fix a typo on the homepage

- doc/SUMMARY.md
It seems that a page should be referenced from the TOC to be really published.
> actually add textmate page

- doc/Composing_Applications.md
Fixes theia-ide/theia#4144
Add troubleshooting for people trying to build Theia behind proxies for
native dependencies built using node-gyp.
Signed-off-by: alainbernard <alain.bernard1224@gmail.com>
> Add doc for building Theia behind proxy

- site/index.html
For some reason, the features paragraph has many elements that get wrapped in `<a name="features"></a>` tags.
I'm not sure why, but this change fixes it.
Currently live:
With this change:
The bug seems to pre-date my recent changes, but I think my `a/div` replacement made it surface again.
> Fix strange features-anchor bug

- site/index.html
The same Theia website is served under at least two URLs:
- https://www.theia-ide.org/
- https://www.theia-ide.org/index.html
This usually results in severe SEO downgrades from search engines like Google.
The good news is that it's pretty easy to fix.
> SEO: Add canonical link

- doc/Composing_Applications.md
I've made this change because Theia Python Extension uses [palantir's Python Language Server](https://github.com/palantir/python-language-server) and not the [sourcegraph one](https://github.com/sourcegraph/python-langserver), which is referenced in the ["Build your own IDE" section of the documentation](https://www.theia-ide.org/doc/Composing_Applications.html).
Closes theia-ide/theia#3422
> Modify Python Language Server link

- netlify.toml
Addresses #38 
This PR adds a [netlify.toml](https://www.netlify.com/docs/netlify-toml-reference/) file to the root of the project in order to re-direct traffic from `/doc` to `/docs`. This netlify.toml file can used to setup more redirect rules in the future, in addition to other things like build/deploy configurations, headers, etc.
> /doc to /docs redirect rules

- src/docs/README.mdx
Fixes #63
Description:
- Remove the reference and badge to `AppVeyor` since
the CI integration no longer exists in the main repository as
of https://github.com/eclipse-theia/theia/pull/6179.
Additional Info
- The badge displayed an old build which was failing meaning
the failed state would always be displayed unless the badge
is removed.
Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>
> [docs] remove reference and badge to AppVeyor

- src/components/DocArrowNavigators.js
- src/docs/Architecture.mdx
- src/docs/Authoring_Extensions.mdx
- src/docs/Authoring_Plugins.mdx
- src/docs/Commands_Keybindings.mdx
- src/docs/Composing_Applications.mdx
- src/docs/Events.mdx
- src/docs/Extensions.mdx
- src/docs/Json_Rpc.mdx
- src/docs/Language_Support.mdx
- src/docs/Preferences.mdx
- src/docs/README.mdx
- src/docs/Services_and_Contributions.mdx
- src/docs/TextMate.mdx
For accessibility reasons, all Links must have a discernible text(name). 
but here for Navigation arrows  Docs. we're using images inside of the link without any label or title on the links.
This PR adds semantic aria-labels and title to the wrapper links.
Now with this change in place if the user is to hover on the arrow due to the added title attribute it shows this:
which in my opinion is kind of better user experience :slightly_smiling_face:
> Added semantic titles and aria-labels to Navigation arrows in the docs for better UX and a11y.

- src/docs/Authoring_Extensions.mdx
Fixes #75
The pull-request updates the documentation for generating the `hello-world` example when using the `generator-theia-extension`.
> docs: fix generator-theia-extension command

- src/docs/README.mdx
Fixes #81
The pull-request updates the license link name. The link itself points to the `theia` main repo's license but still uses Apache 2.0 instead of the correct license EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0. This pull-request addresses that issue so there is no longer any confusion.
> docs: update license link name

- src/docs/Authoring_Extensions.mdx
Fixes #29
Updates information regarding `prerequisites` by pointing to the source of truth
located at the main repository's `Developing.md#prerequisites` section. The prerequisites described in the main repo are also more complete and up-to-date.
> docs: update the prerequisites information

- src/docs/Authoring_Extensions.mdx
- src/docs/Composing_Applications.mdx
Fixes #82
This pull-request:
- removes references to deprecated extensions from the docs
- adds a section in composing applications which references a guide present in the main repo regarding how to consume VS Code extensions.
> docs: remove deprecated extensions

- src/docs/Composing_Applications.mdx
Adding a missing instruction to composing applications guide, without which downloaded plugins cannot be found. Closes #90.
> Adding missing instructions to composing applications

- gatsby-config.js
- src/components/index/Header.js
Fixes #62
- The following pull-request updates the website's header (to include **platform**) in order to be explicit and avoid any potential confusion adopters/users might have about the software. Currently, we only use **Cloud & Desktop IDE** as a header which is incorrect and does not accurately describe the software.
The header and browser tab title should be updated to more explicitly describe the software.
- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)
> website: add 'platform' to header to avoid confusion

- src/docs/composing_applications.md
**Description**
Fixes: #91
The following commit updates the prerequisites documentation to refer to the upstream link instead of maintaining two sources of truth. This will allow documentation to be less outdated.
> documentation: update prerequisites

- LICENSE
- README.md
- package.json
- src/components/DocArrowNavigators.js
- src/components/DocImage.js
- src/components/DocSideBar.js
- src/components/DocTopicChooser.js
- src/components/Footer.js
- src/components/Nav.js
- src/components/index/Banner.js
- src/components/index/ContributorsAndAdopters.js
- src/components/index/Feature.js
- src/components/index/Features.js
- src/components/index/Header.js
- src/components/index/Promo.js
- src/components/index/Promos.js
- src/docs/menu.js
- src/hooks/use-site-metadata.js
- src/layouts/docs-layout.js
- src/layouts/layout.js
- src/pages/404.js
- src/pages/docs.js
- src/pages/index.js
- src/templates/doc.js
- src/utils/data.js
- src/utils/variables.js
This repo is to be moved to the Eclipse Theia project. First we
have to adopt the same license:
EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
This commit adds this license and copyright headers, following
the re-licensing exercise. See here for the details:
https://github.com/theia-ide/theia-website/wiki/Re-licensing-theia-ide-theia-website
Signed-off-by: Marc Dumais <marc.dumais@ericsson.com>
> [Eclipse Foundation] Re-license the repo

- src/docs/composing_applications.md
The screenshot shows "yarn theia start ..." but the example command
missed the "theia" part.
Signed-off-by: Jonah Graham <jonah@kichwacoders.com>
> Fix command line for starting theia in composing applications

- src/docs/blueprint_download.md
**What it does:**
Fixes: #137
The following pull-request fixes the **blueprint documentation** link referenced in the **download** documentation to use the absolute link rather than relative. This fixes a 404 error.
**How to test**
Verify the link is correct.
> blueprint: fix documentation link

- gatsby-config.js
- package-lock.json
- package.json
The following commit adds the `gatsby-autolink-headers` plugin in order to automatically create anchor links in markdown content which can be later used to reference individual sections of the documentation.
- https://www.gatsbyjs.com/plugins/gatsby-remark-autolink-headers/
> Add 'remark-autolink-headers` plugin

- src/docs/authoring_plugins.md
**What it does**
Fixes: #129
The following commit fixes the typedoc link for the `plugins`.
**How to test**
- confirm that the link works in the preview
- navigate to "_Authoring Pugins_"
- click the "_Browse typedoc of plug-ins"_ link
> Fix 129: fix plugins typedoc link

- src/docs/blueprint_documentation.md
- src/docs/blueprint_download.md
* switch mac target from pkg to dmg, because this allows auto-update
-> Website needs to be updated after https://github.com/eclipse-theia/theia-blueprint/pull/94 was merged and the dmg was published for the first itme
> Check for Updates gives no feedback if there is none [macOS]

- src/components/index/Banner.js
- src/components/index/Feature.js
- src/components/index/Header.js
- src/components/index/Promo.js
- src/layouts/layout.js
- Remove different file-based margin-bottom rules for headings and add to .heading-tertiary
> Consistent heading margin

- src/components/index/Features.js
Removed "stack" from "modern tech stack"
#154 
> Alligned column headers

- src/docs/composing_applications.md
Inspired from what we did for Blueprint. In this example,
we keep using the Theia-specific git extension and exclude
the equivalent vscode built-in extensions.
I have also Modified the example start commands, so they
load the plugins.
I have confirmed it works by following the build instructions
Fixes #166
Signed-off-by: Marc Dumais <marc.dumais@ericsson.com>
> Switch example product package.json to extension pack

- src/docs/composing_applications.md
**What it does**
The commit adds `vscode.microsoft-authentication` to the list of plugins
to exclude (as part of `theiaPluginsExcludeIds`). The commit also adds
some high-level information regarding the possible configuration options
for consuming plugins:
- `theiaPluginsDir`
- `theiaPlugins`
- `theiaPluginsExcludeIds`
> docs: update `theiaPluginsExcludeIds`

- src/docs/blueprint_download.md
Adds a section to the Blueprint documentation with links to the forums and to the support page.
Signed-off-by: Maximilian Koegel <mkoegel@eclipsesource.com>
> Added support section to Theia Blueprint documentation

- src/docs/i18n.md
- src/docs/menu.js
Explains in depth how to use the `nls.localize` function and the utilities that the frameworks provides to localize a Theia extension.
> Add documentation on i18n

- src/docs/i18n.md
Fixes an error in the documentation, noticed due to https://github.com/eclipse-theia/theia/discussions/10637.
> docs: Bind `LocalizationContribution` in the backend

- src/components/Support.js
We've updated the structure of our website. Although the previous link still works (the user is redirected), updating is a good idea nonetheless.
> Update TypeFox support link

- src/components/Blogs.js
- Using the browsers fetch API instead of the rss-parser's parseURL method to avoid CORS error.
Closes #285
> Using fetch API for Blogs

- src/docs/i18n.md
Since a lot of questions came in recently on the discourse forum regarding default locales, I decided to write a short section on that.
Also changes a headline to use the correct header capitalization.
> Document how to change default locale

- gatsby-node.js
- package-lock.json
- package.json
- src/components/index/ContributorsAndAdopters.js
- src/pages/index.js
Previously the list of Contributors & Adopters was queried from the Eclipse Foundation
API after the initial rendering of the landing page. Once they were loaded they were
inserted leading to a layout shift. This was especially noticeable when visting the page
via an anchor as the content moved out of the frame.
This is now fixed by determining the list of Contributors & Adopters at build time.
As they are no longer loaded dynamically the layout shift is avoided. Additionally we no
longer need to wait for the API call to finish when visting the website, improving the
load times.
The website needs to be rebuilt whenever the Contributors & Adopters list shall be
updated. Should the API call fail the website build will panic to avoid publishing the
website with an incomplete list. …
> Prevent layout shifting of landing page

- src/docs/authoring_vscode_extensions.md
- src/docs/composing_applications.md
- src/docs/menu.js
Fixes https://github.com/eclipse-theia/theia-website/issues/316
Contributed on behalf of STMicroelectronics.
> doc: Add page on authoring VS Code extensions

- src/docs/authoring_vscode_extensions.md
- src/layouts/docs-layout.js
In this change we like to make it more clear that the steps documented for deploying own VS Code extensions also applies to third-party extensions.
Also adds missing styling for ordered lists.
Contributed on behalf of STMicroelectronics.
> Clarify doc also applies to third party extensions

- src/components/Releases.js
As requested by @planger on [cdt-cloud-dev](https://www.eclipse.org/lists/cdt-cloud-dev/msg00010.html) here is the entry for cdt-gdb-adapter and related parts of CDT.cloud for Theia 1.29 release.
> Add cdt-gdb-adapter to compatible components

- src/components/index/GettingStarted.js
- src/components/index/Header.js
- src/docs/blueprint_download.md
Update the try now url to the proper URL try.theia-cloud.io
**Note:** This depends on changes to the Try Now cluster deployment. Consequently, merging this should be coordinated with @jfaltermeier to avoid downtimes of the Try Now button
> Update try now URL

- src/docs/commands_keybindings.md
The current link to the [CommonMenus Typedoc](https://eclipse-theia.github.io/theia/docs/next/modules/core.CommonMenus-1.html) doesn't work (anymore?). This change fixes the link.
Contributed on behalf of STMicroelectronics.
> Fix link to CommonMenus Typedoc

- src/docs/json_rpc.md
Updates the outdated documentation for setting up RPC services by
- Removing any notion of the old vscode json-rpc protocol. The neutral term RPC is used instead
- Replacing the outdated loggingServer example with a current version of the taskServer
- Removing sections of the documentation that are now obsolete because the underlying framework code has been reworked
Note: he code snippets are based on https://github.com/eclipse-theia/theia/pull/12581. So this PR is blocked until  the  referenced PR is approved and merged
Part of https://github.com/eclipse-theia/theia/issues/12368
> Update RPC documentation

- README.md
- src/components/Releases.js
Whereas there is a redirect in place, it adds a bit of a waiting time to forward users from eclipse.org/<project> to eclipse.dev/<project>. Thus, it is better to directly link to the eclipse.dev URL.
More information on this migration can be found at https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3069
> Switch Eclipse project links to eclipse.dev

- src/docs/blueprint_download.md
Allow people to read the `help us` more clearly by separating it from the larger text block.
> Move "help us" to own section

- src/components/Releases.js
Add `@eclipse-emfcloud/jsonforms-property-view` module versions to compatible technologies section
> Update compatible technologies with EMF.cloud modules for CR 1.43.1

- src/docs/consume_theia_fixes_master.md
- src/docs/menu.js
Provides guidance on how a Theia app developer can locally pick up a fix/feature in the Theia codebase prior to the fix being in a release.
Co-authored with Jonas Helming
> New markdown: consuming theia fixes

- src/components/Releases.js
Add `@eclipse-emfcloud/jsonforms-property-view` module versions to compatible technologies section
> Update compatible technologies with EMF.cloud modules for CR 1.45.1

- src/docs/getting_started.md
This hyperlink failed to use the theia-ide.org domain to be reachable on the internet.
> Fixed broken documentation link in getting_started.md

- .github/workflows/publish.yml
As soon as we switch over to theia-ide.org, we are not running under a subdirectory anymore (`/theia-website`). So we need to remove the path prefix before switching over the DNS. Until the final switch (which I've already triggered via the EF), the website links won't work. But that's fine as they should start working again as soon as theia-ide.org points to the GH page.
> Remove path prefix in prep for DNS switch

- README.md
- gatsby-config.js
- package-lock.json
- package.json
- src/docs/authoring_extensions.md
- src/docs/authoring_plugins.md
- src/docs/authoring_vscode_extensions.md
- src/docs/blueprint_documentation.md
- src/docs/commands_keybindings.md
- src/docs/composing_applications.md
- src/docs/enhanced_tab_bar_preview.md
- src/docs/extensions.md
- src/docs/getting_started.md
- src/docs/json_rpc.md
- src/docs/label_provider.md
- src/docs/language_support.md
- src/docs/services_and_contributions.md
- src/docs/tasks.md
- src/docs/tips.md
- src/docs/toolbar.md
- src/docs/user_getting_started.md
- src/docs/user_install_vscode_extensions.md
- src/docs/user_toolbar.md
- src/docs/widgets.md
On hard reload the URL ending with `xyz/` sometimes becomes `xyz`, which then breaks all relative internal  links. With this change, we are adding `gatsby-plugin-catch-links` to ensure internal links work either way. Also we update the readme to reflect where the website is now hosted.
> Fix link issues after hard-reloading pages

- src/docs/blueprint_documentation.md
Contributed on behalf of Pragmatiqu IT GmbH
Should only be merged once Theia `1.49.0` is released.
> Add splash screen documentation

- src/components/Resources.js
- src/components/index/Header.js
> Add Theia IDE introductions

- src/components/Releases.js
Sorry for being a little late with this update. I have tried this time to limit the information to the essential: the Theia extension to view traces. The other modules used underneath can easily be found in the linked repo or the npm page for the extension.
> theia-trace-extension update for community release 1.52.0

- src/docs/blueprint_documentation.md
> Clarify nested property structure

- src/docs/authoring_extensions.md
- src/docs/authoring_vscode_extensions.md
- src/docs/composing_applications.md
> Remove manual approach from composing application docu

- src/components/index/TheiaIDEDownloads.js
> Add Snap Download as preferred option

- src/docs/theia_ai.md
- src/docs/user_ai.md
> Extend Theia AI docu that specific models might require customization

- src/components/Releases.js
Add @eclipse-emfcloud/jsonforms-property-view module version to compatible technologies section
> Update compatible technologies with EMF.cloud modules for CR 1.55.x

- gatsby-config.js
- src/layouts/basehead.js
- src/layouts/headwithIDEschema.js
- src/layouts/headwithPlatformschema.js
- src/pages/index.js
fixed #682
All other pages show the platform meta data for now.
> Add sepecific meta data for IDE page

- src/components/Releases.js
This release was correct at the time of writing, because I didn't realize that cdt-gdb-vscode was not updating on openvsx. This has since been resolved (see https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/issues/125#issuecomment-2544032355)
> Update release of GDB Adapter

- src/docs/blueprint_download.md
The Theia Blueprint project has been renamed/replaced by Theia IDE. The page dedicated to Blueprint now only provides a link to redirect visitors to the information about Theia IDE.
Previously that link lead to the documentation home page. Although that page does contain a mention (of sorts) of the IDE, it is clear that it is not the intended target of the link because the link contains the `theiaide` fragment, but there is no anchor with that ID on the documentation home page. There is an anchor with that ID on the website home page, and it is that section of the website that the link was intended to target.
> Correct Blueprint redirect link

- src/docs/user_ai.md
In the AI User Documentation, there was only little information about the limited context size of the Ollama connector and how to configure it via the requestSettings.
Plus, the section about the requestSettings was outdated as the settings structure has changed in the meantime (especially regarding the `scope` key). 
This PR addresses both of these issues by adding some details to the Ollama connector section and by updating the example and documentation in the _Custom Request Settings_ section.
> Clarify/update Ollama and Request Settings sections in the AI User Documentation

- src/components/Releases.js
This PR reverts the applicable trace viewer extension for Theia 1.64.x to "TBD". 
Unfortunately, the theia traceviewer extension v0.9.1 is confirmed to not be compatible with Theia 1.64.1. It will need to be updated, but we have no ETA right now.
> Update trace viewer info: TBD for Theia 1.64.x
