package-lock.json, package.json
Partially addresses #8.
The other packages do not propose fixed versions yet.
Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>
=> [security] Updated some packages

doc/Composing_Applications.md, doc/SUMMARY.md
[Rendered](https://github.com/theia-ide/theia-website/blob/54a2b72b17fb15bc8f9064b089a263ce9d79a2b5/doc/Composing_Applications.md)
=> add Build your own IDE section

doc/Language_Support.md, doc/SUMMARY.md, doc/TextMate.md
Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>
=> Add TextMate contribution documentation

site/index.html
=> Various website improvements

doc/Authoring_Plugins.md
Add useful external links for plug-ins
Change-Id: I6d39528b4d11215bac020626835ce89d442d39eb
Signed-off-by: Florent Benoit <fbenoit@redhat.com>
=> [plug-in] Add plug-in typedoc link and comparison table of VsCode/Theia of plug-ins on website

doc/Authoring_Extensions.md, doc/Composing_Applications.md
Motivated by https://github.com/theia-ide/theia/issues/5123#issuecomment-508221237
=> [prerequisites] node 10 instead of 8

src/components/Nav.js
Signed-off-by: nisarhassan12 <syednisarhassan12@gmail.com>
=> Fixes  Nav.

src/docs/README.mdx
Fixes theia-ide/theia-website#32
Signed-off-by: Sven Efftinge <sven.efftinge@typefox.io>
=> replace gitter with spectrum

src/components/DocArrowNavigators.js, src/components/DocSideBar.js, src/components/Footer.js, src/layouts/layout.js, src/pages/index.js
This PR fixes most parts of #40
=> Layout improvements

README.md, src/components/DocSideBar.js, src/components/Footer.js, src/components/Nav.js, src/docs/Authoring_Plugins.mdx, src/docs/Json_Rpc.mdx, src/docs/README.mdx, src/docs/Services_and_Contributions.mdx, src/pages/index.js
https://github.com/theia-ide/theia → https://github.com/eclipse-theia/theia
=> Update to Theia's new repository URL

src/components/DocSideBar.js
Fixes theia-ide/theia-website#56
This is what it looks like now. I think that it's more descriptive and clear then what it was before
Signed-off-by: Nisar Hassan Naqvi <syednisarhassan12@gmail.com>
=> Updated DocSideBar Subsection Styling.

.env.development, package.json
This PR configures Graphql Playground which is essentially a wrapper  over GraphiQL but includes additional features such as:
1. Interactive, multi-column schema documentation
2. Automatic schema reloading
3. Support for GraphQL Subscriptions
4. Query history
5. Configuration of HTTP headers
6. Tabs
7. Extensibility (themes, etc.)
This is what it looks like:
I think it's worth adding to the project as it enhances the DX.
=> Replaces Graphiql with Graphql Playground.

src/components/DocTopicChooser.js, src/components/Nav.js, src/layouts/docs-layout.js
Signed-off-by: Nisar Hassan Naqvi <syednisarhassan12@gmail.com>
=> Fixes theia-ide/theia-website#76

src/layouts/docs-layout.js, src/utils/variables.js
Fixes #67 
I have darkened the colours by a bit and now the problem is gone.
=> Fixed Contrast Issues.

.gitpod.yml
This PR adds vscode extensions for CSS-IN-JS support (i.e for things like IntelliSense & syntax highlighting & so on).
=> [setup] add: extensions for css-in-js support.

src/components/Nav.js
Fixes theia-ide/theia-website#83
=> [Nav] Fix the SSR issue.

src/components/index/Promos.js
=> Rephrase 'Flexible Layout'

src/components/Footer.js
Fixes theia-ide/theia-website#105
=> [footer] update the copyright date.

.gitpod.yml
Fixes theia-ide/theia-website#109
=> gitpod-setup fix the start task.

.gitignore, package-lock.json
Fixes theia-ide/theia-website#116
Signed-off-by: Nisar Hassan Naqvi <syednisarhassan12@gmail.com>
=> put package-lock.josn under version control.

src/docs/composing_applications.md
=> Replace "too" with "to"

src/components/index/Header.js
* enable "Try on Desktop" button on front page
Signed-off-by: Johannes Faltermeier <jfaltermeier@eclipsesource.com>
=> Theia blueprint documentation and download page #131 #134

src/docs/blueprint_download.md
=> Fixed typo on blueprint page

src/components/index/Header.js
* remove "Try in Gitpod" button for now
* closes #148
Signed-off-by: Johannes Faltermeier <jfaltermeier@eclipsesource.com>
=> Try in Gitpod button on Website links to Gitpod VS Code announcement

src/docs/blueprint_documentation.md
See https://github.com/eclipse-theia/theia-blueprint/pull/88
Signed-off-by: Paul Maréchal <marechap.info@gmail.com>
=> align documentation with theia-blueprint

src/components/index/Features.js, src/components/index/Header.js, src/resources/icon-html.svg
#154
Described benefits more explicit, added forth item "modern tech"
=> Rephrased feature section

src/docs/composing_applications.md
fixed #163
Tested running product, worked fine for me.
=> Updated example product

package.json, src/components/Nav.js, src/components/index/Header.js, src/components/index/Products.js, src/layouts/layout.js
- Move logo to Nav
- Move gh-iframes to top-right, below Nav
- Display buttons next to text on big screens
- Show products in a Slider
- Show Popup on click on Product
Product sources still need to be updated, as well as preview and high-res images provided
=> Refactor layout of home page

src/components/index/Products.js
=> Change cursor to pointer on thumbnails

src/components/index/Header.js
=> Repositioning of Header Buttons

src/components/index/Products.js
=> Add breakpoint for single product on mobile

src/components/index/Products.js, src/layouts/layout.js
Add button to close the popup
Closes #175
=> Add x button to popup

src/components/Footer.js
Changed copyright to Eclipse Foundation, added about link
see #154
=> Updated footer

src/components/Nav.js, src/components/Support.js, src/pages/support.js
- Add subpage for support
- Random order of support providers
=> Add support page

src/components/Support.js
=> Fix random ordering

src/docs/blueprint_download.md
needs to be merged once we finalize the beta release
=> Update Theia Blueprint release information from alpha to beta

src/components/Support.js
=> Restyling of support page

src/components/Nav.js, src/components/Support.js, src/pages/support.js
- Add subpage for support providers
- Random order of support providers
fixed #157
=> GH-157 - Add support page

package-lock.json, package.json
=> Pinned swiper version to 6.x

src/docs/commands_keybindings.md, src/docs/menu.js
=> Improve Commands, Keybindings and Menu docu

src/docs/backend_application_contribution.md, src/docs/menu.js
Fixes https://github.com/eclipse-theia/theia-website/issues/203
Signed-off-by: Philip Langer <planger@eclipsesource.com>
=> Add documentation on backend application contrib

src/layouts/docs-layout.js
=> Reduce whitespace after ul in documentation

README.md, package.json
Fixes #218
- `--host=0.0.0.0` has been added directly inside the script
- Build for production and serve info has been added to README
=> Change npm run start and add info to README.md

src/docs/extensions.md
=> Added link to coverage report

src/components/index/Header.js
=> Added Hackathon

src/components/index/Header.js
=> Removed Hackathon banner

src/docs/authoring_plugins.md, src/docs/extensions.md
Fixes: https://github.com/eclipse-theia/theia-website/issues/249.
=> doc: fix broken comparator link

src/components/index/Header.js
=> Replaced link to release 1.0 with latest release

src/components/Support.js
Add (optional) 'sponsored development' parameter for supporting companies as url.
Signed-off-by: Max Elia Schweigkofler max_elia@hotmail.de
=> Add 'sponsored development' link

src/components/index/Products.js
=> Add controls for "Selected Theia Tools"

src/components/index/Header.js
=> Changed latest release to 1.22

src/components/index/Header.js
=> Added mailing list and twitter to header

src/docs/menu.js, src/docs/tips.md
Signed-off-by: robmor01 <Rob.Moran@arm.com>
This PR adds a `Professional Tips` section to the website including the VS Code / Theia Extension upgrade example
=> Add advanced tips section

src/components/index/Header.js
=> Updated latest release to 1.23

src/components/Resources.js, src/resources/article.svg, src/resources/video.svg
=> Exchange icons

src/components/index/Products.js
Fixes #262
- Add `user-select: none` property to Products in carousel
=> Improve behavior of picture gallery

package.json, src/components/Blogs.js, src/components/Nav.js, src/components/Resources.js, src/pages/blogs.js, src/pages/resources.js, src/resources/article.svg, src/resources/video.svg
=> Added resource pages to website

src/docs/composing_applications.md, src/docs/menu.js
=> Refined build you own IDE section

src/docs/architecture.md, src/docs/getting_started.md, src/docs/menu.js
=> Added getting started

src/components/Resources.js
=> Add recent articles to resource section

src/docs/authoring_plugins.md
Fixes https://github.com/eclipse-theia/theia-website/issues/273
=> Fix broken link

src/components/Resources.js, src/components/index/IntrosToTheia.js, src/utils/data.js
=> Added getting started with Eclipse Theia talk

src/components/Resources.js, src/components/index/Header.js
=> Added recent release articles

src/components/index/Header.js
* link to Theia.cloud example
* make button max-width slightly bigger to fit label
=> Readd a try Theia online button

src/components/Resources.js, src/components/index/Header.js
=> Add links to new release articles

src/components/Releases.js
=> Adapt community release plan

src/components/Releases.js
=> Adapt release announcement date

src/components/Resources.js, src/components/index/Header.js
=> Add links to Theia release 1.30

src/components/Releases.js, src/components/Resources.js, src/components/index/Header.js
=> Add links to community release annoucement

src/components/Releases.js
=> Fix release page

src/components/index/Header.js
=> Add registration link for TheiaCon

src/components/index/GettingStarted.js, src/docs/blueprint_download.md
=> Add links to "try it online"

src/components/Resources.js, src/components/index/Header.js
=> Add 1.31 N&N

src/components/Releases.js
=> Add 2023-01 community release plan

src/docs/user_install_vscode_extensions.md
=> Add details about VS Code compatibility

src/components/index/Header.js
=> Add Hackthon to banner

src/components/index/Header.js
=> Removed TheiaCon, Add recordings

src/components/Resources.js
=> Add community release celebration video

src/components/index/Header.js
=> Add 1.32 release announcement

src/docs/blueprint_documentation.md
This is a start of talking about preference customization specific to theia-blueprint.
=> Theia-blueprint: Add Preference Customization

src/components/Releases.js
=> Adapt community release date

src/components/Resources.js, src/components/index/Header.js
=> Remove Hackathon, add birthday

src/components/Resources.js, src/components/index/Header.js
=> Add 1.33 release announcement

src/utils/data.js
=> Update "Getting started" talk on main page

src/components/Resources.js
=> Add news section to resources

src/components/index/Header.js
Closes: https://github.com/eclipse-theia/theia-website/issues/390.
=> Add 1.34 release announcement

src/components/Releases.js
- Add published EMF.cloud modules to compatible technologies section
=> Update compatible technologies with EMF.cloud modules for CR 1.34.x

src/components/index/Products.js
Implements: #334
Signed-off-by: Niklas DAHLQUIST <niklas.dahlquist@st.com>
=> Display product names in slider

src/components/Releases.js
@jonahgraham Can you please confirm the versions I put in for cdt-gdb-adapter?
=> Add cdt-gdb-adapter version for Theia 1.34

src/components/Releases.js
=> Add link to community release announcement

src/docs/composing_applications.md
=> composing-applications: `next` changed to `latest`

src/components/Releases.js
=> Add new community release

src/components/index/Header.js
Eclipse Theia community release 1.34.x
Latest release: Eclipse Theia 1.36
=> Fix links to latest release and community release

src/components/Releases.js
=> Fix dates for 2023-05 community release

src/components/Releases.js
- Add published EMF.cloud modules to compatible technologies section
=> Update compatible technologies with EMF.cloud modules for CR 1.37.1

src/components/Releases.js
=> Update CDT Cloud Debug Adapter version for Theia 1.37

src/components/Releases.js, src/components/Resources.js, src/components/index/Header.js
=> Add recent release announcements

src/components/Releases.js
Fixes #431.
Signed-off-by: Marco Miller <marco.miller@ericsson.com>
=> Releases: Add Theia Trace Extension to 1.37 (#431)

src/components/Releases.js, src/components/index/Header.js
=> Add community release 2023-05

src/components/Releases.js
Planned information about next community release, fixes #433
=> Add planned release 1.40.x (#433)

src/components/Releases.js, src/utils/data.js
Sorry, I found one more broken link and one more eclipse.org link. Thank you!
=> Fix broken CDT Cloud link and eclipse.org link

src/components/Resources.js, src/components/index/Header.js
=> Add Theia 1.40 release announcement

src/components/Releases.js
- Add published EMF.cloud module versions to compatible technologies section
=> Update compatible technologies with EMF.cloud modules for CR 1.40.0

src/components/Releases.js
=> Update 2023-08 community release state

src/components/Releases.js
Updates the version of Langium and Sprotty for the next Theia community release.
=> Update Langium and Sprotty version

src/components/Resources.js, src/components/index/Header.js
=> Add 1.41 release

src/components/Releases.js
@planger this is what I expect it to be - I need a day to test it.
=> Update debug adapter to latest release

src/components/Resources.js
=> Add Theia vs Code OSS comparison

src/components/Releases.js
Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>
=> Releases: Add Theia Trace Extension to 1.40

src/components/Releases.js, src/components/Resources.js, src/components/index/Header.js
=> Add community release

src/components/index/Header.js
=> Adapt TheiaCon announcement

src/components/Resources.js, src/components/index/Header.js
=> Add 1.42 release announcement

src/components/Releases.js
=> Add Community release 2023-11

src/components/Resources.js, src/components/index/Header.js
=> Add 1.43 release announcement

src/components/index/Header.js
=> Remove TheiaCon

src/components/Resources.js, src/components/index/ContributorsAndAdopters.js
=> Add how to get listed as an adopters or contributor

src/components/index/Header.js
Adjust TheiaCon date to comply with the actual ending day...
=> Correction for TheiaCon 2023 end-date

src/components/Releases.js, src/components/index/Header.js
=> Add 1.44 release

src/components/Releases.js
See https://www.npmjs.com/package/langium
=> Add langium 2.1.3 to the community release

src/components/Releases.js, src/components/index/Header.js
=> Add 1.45 release

src/components/index/Header.js
fixed #494
@tsmaeder This was the issue you observed on the other PR, I was too blind to see it and then I convinced you to be blind, too :-D
=> Fix duplicate text in header

src/docs/user_getting_started.md
=> Add how to run Theia IDE with docker link

src/components/Releases.js
Minor fix to show the correct year for next planned community release 1.45.x
=> Fix year for 1.45.x planned

src/docs/events.md
=> Fix heading structure in events docu

src/components/Nav.js
=> Change community link to GitHub Discussions

src/components/Releases.js
Updated published state for release 1.45.x
=> Update 1.45.x to published

src/docs/authoring_extensions.md
@JonasHelming  Please review the proposed changes.
=> Add overview paragraph to Authorizing Theia extensions doc

src/components/Releases.js
Update announcementurl of Theia 1.45.x
=> Add url to announcement blog of v1.45.x

src/components/Releases.js
=> Add 1.46 release post

src/components/Releases.js
=> Add dates for community release 2024-05

src/components/index/Header.js
=> Remove community call announcement

src/components/index/TheiaIDEDownloads.js
=> Add link to Docker image

src/components/Releases.js
=> Add 1.47 release announcement

src/components/index/Header.js
fixed #543
(the link seems wrong, but this is a mistake in publishing)
=> Add 1.48 release

src/components/Releases.js
Add release announcement for Theia 1.48
=> Add 1.48 release announcement

src/components/Releases.js, src/components/index/Header.js
=> Add 1.49 release announcement

src/docs/contribution_filter.md, src/docs/menu.js
=> Add docu for contribution filters

src/components/Releases.js
Add @eclipse-emfcloud/jsonforms-property-view module version to compatible technologies section
=> Update compatible technologies with EMF cloud modules for CR 1.49.1

src/components/Releases.js, src/components/index/Header.js
=> Add new community release 2024-08

src/components/index/Header.js
Update ref in header to Theia 1.50 announcement 
=> fix: Added ref to 1.50 release in header

src/components/index/TheiaIDEDownloads.js, src/components/index/TheiaIDEHeader.js
=> Remove Beta from Theia ide

src/components/Releases.js, src/components/index/Header.js
=> Add 1.51 release

src/components/Resources.js
=> Add TheiaCon Talk Recordings

src/components/Releases.js
Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>
=> theia-trace-extension update for community release 1.49.x

src/utils/data.js
=> Change Blueprint to Theia IDE in products

src/components/Resources.js
=> Add Theia IDE vs VS Code article

src/components/Releases.js, src/components/index/Header.js
=> Add 1.52 release

src/components/index/Header.js
=> Add TheiaCon 2024

src/docs/composing_applications.md
=> Fixed "Build your own tool" page

src/components/Releases.js
Add Theia 1.55 release
Set Theia 1.52 to published
=> Add Theia 1.55 release

src/components/Releases.js
Updates the compatible sprotty and Langium versions for the latest release
=> Update release tech

src/components/Releases.js
Add @eclipse-emfcloud/jsonforms-property-view module version to compatible technologies section
=> Update compatible technologies with EMF.cloud modules for CR 1.52.0

src/components/Releases.js, src/components/index/Header.js
=> Add 2024-08 community release

src/components/Resources.js
=> Add Theia AI article

src/components/Releases.js
Announce the release of Theia v1.53.0 to the public.
=> Notify Theia v1.53.0 release to public

src/components/Resources.js
=> Add Theia AI articles

src/docs/widgets.md
- content seems to be .tsx not .ts
- typo in the widget command
=> doc: Update widgets.md

src/docs/blueprint_documentation.md, src/docs/user_getting_started.md
=> Fix links to docker image

src/components/Resources.js
=> Add Code Real Time adopter story

src/components/Releases.js
Added monthly release Theia 1.54
=> Notify Theia v1.54.0 release to public

src/components/Resources.js, src/docs/theia_ai.md, src/docs/user_ai.md
=> Add latest Theia AI articles

src/components/index/TheiaIDEDownloads.js
=> Add snap store download

src/components/index/Header.js
=> Make TheiaCon Logo responsive

src/components/index/TheiaIDEHeader.js
=> Improve Theia IDE Header

src/docs/user_ai.md
=> Add docu for llamafile

src/docs/user_ai.md
=> Document new option for custom OpenAI

src/components/Resources.js
=> Add new Theia AI articles

src/components/index/Header.js
=> remove TheiaCon Banner

src/components/Releases.js
Updated monthlyReleases section with "Eclipse Theia 1.55 Release: News and Noteworthy" updates.
=> update Releases.js 

src/components/Blogs.js
=> Add link to RSS feed

src/docs/user_ai.md
=> Add docu on custom request settings

src/docs/user_ai.md
=> Document new code completion settings

src/components/index/TheiaIDEFeatures.js
=> Make contributor box under Theia IDE responsive

src/components/index/CommonNews.js
=> Add 1.56 release

src/components/Releases.js
Add announcement blog URL in monthly releases -> v1.56.0
=> Add url to announcement blog of v1.56.0

src/docs/commands_keybindings.md, src/docs/preferences.md, src/docs/widgets.md
=> Fixed links

src/components/Releases.js, src/components/index/CommonNews.js
=> Add 2024-11 community release

src/components/Releases.js
=> fix for planned date for v1.58

src/components/Resources.js
=> Add OCT press release

src/components/Resources.js, src/components/index/CommonNews.js
=> Add theiaCon videos

src/components/Releases.js, src/components/index/CommonNews.js
=> Add 1.57 release

src/components/index/Features.js, src/components/index/TheiaIDEExtensible.js, src/docs/composing_applications.md, src/docs/project_goals.md
=> Clarify that Theia is not a VS Code fork

src/docs/user_ai.md
fixed #692
see https://github.com/eclipse-theia/theia/pull/14669
=> Fix keybinding for trigger inline suggestion

src/components/index/CommonNews.js
=> Add 1.58 release

src/components/Releases.js
=> Add url to announcement blog for v1.58.0

src/docs/index.md
=> fix license link

src/docs/user_ai.md
=> Clarify LLM provider state and supported features

src/docs/user_ai.md
This should avoid complications in the longrun and the issue is documented.
=> Add note regarding uvx install

src/docs/user_ai.md
=> Document new auto start behavior

src/components/index/TheiaIDEDownloads.js
=> Add waning about Mac Arm instability and performance

src/components/Releases.js
Add @eclipse-emfcloud/jsonforms-property-view module version to compatible technologies section
=> Update compatible technologies with EMF.cloud modules for CR 1.58.x

src/components/index/TheiaIDEDownloads.js
fixed #732
@tsmaeder Please insert correct link
=> Add new experimental Arm Build for Theia IDE

src/components/Releases.js
=> Add link to monthly release 1.59

src/components/index/TheiaIDEDownloads.js
* Add new signed Arm Build for Theia IDE
fixed #732
=> Add new signed Arm Build for Theia IDE

src/components/index/CommonNews.js
=> Add 1.59 release

src/components/index/TheiaIDEDownloads.js
=> Add comment about Snap and move to second line

src/docs/theia_ai.md, src/docs/theia_coder.md, src/docs/user_ai.md
=> Add links to Theia AI articles

src/docs/user_ai.md
=> Refined set-up for user Ai docu

src/docs/user_ai.md
=> Update code completion docu

src/components/Releases.js, src/components/index/CommonNews.js
=> Update community release

src/components/index/TheiaAIFeatures.js
=> Fix broken links

src/components/Support.js
=> Update EclipseSource Support offering

src/docs/theia_ai.md, src/docs/user_ai.md
=> Link from Theia AI to Theia IDE

src/docs/user_ai.md
=> Add links to Anthropic and OpenAI API Accounts

src/components/Releases.js
Update the version numbers and module details for GLSP, CDT Cloud Debug Adapter, Langium, and Trace Viewer.
=> Add version information for community releases

src/components/Resources.js, src/docs/theia_coder.md
=> Add Theia Coder Video

src/components/Releases.js
=> Add url announcement blog for v1.60.0

src/docs/data_usage_telemetry.md, src/docs/menu.js
To be reviewed by all project leads
Follow-up: Add Link to the Theia IDE
=> Add data and telementry information

src/docs/theia_ai.md
See: https://github.com/eclipse-theia/theia/discussions/16295
=> Update Theia AI Doc
